/* global window */
// Auto-generated by scraper.py — praca.pl IT jobs

const SKILL_GROUPS = [
  {
    "name": "Development",
    "skills": [
      "React",
      "Vue",
      "TypeScript",
      "JavaScript",
      "Node.js",
      "Python",
      "Go",
      "Java",
      "PHP",
      "SQL",
      "GraphQL",
      "Next.js"
    ]
  },
  {
    "name": "Design",
    "skills": [
      "Figma",
      "UI/UX",
      "Prototyping",
      "Illustration",
      "Motion",
      "Adobe XD"
    ]
  },
  {
    "name": "Marketing",
    "skills": [
      "SEO",
      "Content",
      "Email campaigns",
      "Analytics",
      "Performance",
      "Brand"
    ]
  },
  {
    "name": "Analytics",
    "skills": [
      "SQL",
      "Power BI",
      "Tableau",
      "Excel",
      "Python",
      "A/B tests"
    ]
  },
  {
    "name": "Management",
    "skills": [
      "Agile",
      "Scrum",
      "Product",
      "Team management",
      "OKR"
    ]
  }
];

const JOBS = [
  {
    "title": "Privacy Data Analyst with German",
    "company": "Unknown",
    "logo": "P",
    "location": "Kraków · On-site",
    "salary": "7 000 - 8 000 złbrutto/mies.",
    "type": "pełny etat",
    "posted": "2 godz. temu",
    "match": 90,
    "tags": [
      "Go",
      "AWS",
      "AI",
      "iOS"
    ],
    "why": "Matched from praca.pl IT listings",
    "featured": true,
    "description": "View full job description on praca.pl.",
    "url": "https://www.praca.pl/privacy-data-analyst-with-german_10988512.html#c412c29abfa643336d03a767190e0526",
    "id": 1
  },
  {
    "title": "Remote Content Analyst with Spanish​​",
    "company": "Unknown",
    "logo": "P",
    "location": "Kraków · Remote",
    "salary": "41,00 złbrutto/godz.",
    "type": "Full-time",
    "posted": "2 godz. temu",
    "match": 82,
    "tags": [
      "Go",
      "AWS",
      "REST",
      "AI"
    ],
    "why": "Matched from praca.pl IT listings",
    "featured": false,
    "description": "View full job description on praca.pl.",
    "url": "https://www.praca.pl/remote-content-analyst-with-spanish_10988569.html#c412c29abfa643336d03a767190e0526",
    "id": 2
  },
  {
    "title": "Inżynier / Inżynierka Budowy (branża drogowa) (k/m)",
    "company": "Unknown",
    "logo": "P",
    "location": "Łódź · On-site",
    "salary": "Negotiable",
    "type": "pełny etat",
    "posted": "1 godz. temu",
    "match": 76,
    "tags": [
      "Go",
      "AI"
    ],
    "why": "Matched from praca.pl IT listings",
    "featured": false,
    "description": "View full job description on praca.pl.",
    "url": "https://www.praca.pl/inzynier-inzynierka-budowy-branza-drogowa-k-m_11003059.html#c412c29abfa643336d03a767190e0526",
    "id": 3
  }
];

Object.assign(window, { SKILL_GROUPS, JOBS });