# Generated by Django 5.2.14 on 2026-05-27 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, default='', max_length=255)),
                ('active_tags', models.JSONField(blank=True, default=list)),
                ('format', models.CharField(blank=True, default='all', max_length=20)),
                ('min_match', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
