# Generated by Django 5.2.14 on 2026-05-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0003_savedvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedvacancy',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='savedvacancy',
            unique_together={('user', 'job')},
        ),
        migrations.RemoveField(
            model_name='savedvacancy',
            name='url',
        ),
    ]
